version: "3"
services:
  deltabot:
    image: ghcr.io/dfuchss/deltabot
    restart: unless-stopped
    volumes:
      - ./config:/usr/src/bot/config
      - ./states:/usr/src/bot/states
    environment:
      - DISCORD_TOKEN=$DiscordToken
    networks:
      - deltabot
    depends_on:
      - deltabot-nlu

  deltabot-nlu:
    image: ghcr.io/dfuchss/deltabot-nlu
    restart: unless-stopped
    expose:
      - 5005
    networks:
      - deltabot

# Our docker network!
networks:
  deltabot: