version: "3"
services:
  deltabot:
    image: ghcr.io/dfuchss/deltabot
    restart: unless-stopped
    volumes:
      - ./config:/usr/src/bot/config
      - ./states:/usr/src/bot/states
    environment:
      - DISCORD_TOKEN=$DISCORD_TOKEN
    networks:
      - deltabot
    depends_on:
      - deltabot-duckling

  deltabot-duckling:
    image: rasa/duckling
    restart: unless-stopped
    expose:
      - 8000
    networks:
      - deltabot

# Our docker network!
networks:
  deltabot: