version: "3"
services:
  deltabot:
    image: ghcr.io/dfuchss/deltabot
    restart: unless-stopped
    volumes:
      - ./data:/usr/src/bot/data
    environment:
      - DISCORD_TOKEN=$DISCORD_TOKEN
    networks:
      - deltabot
    depends_on:
      - deltabot-nlu

  deltabot-nlu:
    image: ghcr.io/dfuchss/deltabot-nlu
    restart: unless-stopped
    expose:
      - 5005
    networks:
      - deltabot

  deltabot-duckling:
    image: ghcr.io/dfuchss/duckling
    restart: unless-stopped
    expose:
      - 8000
    networks:
      - deltabot

# Our docker network!
networks:
  deltabot: