version: "3"
services:
  deltabot:
    image: ghcr.io/dfuchss/deltabot
    restart: unless-stopped
    volumes:
      - ./config.json:/config.json
      - ./states:/usr/src/app/states
      - ./rasa-unknown:/usr/src/app/rasa-unknown
    environment:
      - CONF_FILE=/config.json
      - DiscordToken=$DiscordToken
    networks:
      - deltabot
    depends_on:
      - deltabot-nlu

  deltabot-nlu:
    image: ghcr.io/dfuchss/deltabot-nlu
    restart: unless-stopped
    expose:
      - 5005
    networks:
      - deltabot

# Our docker network!
networks:
  deltabot: